### ISSUE TITLE
read soc temperature

### ISSUE THREAD

**Issue by offizium-berndstorath** [RAKWireless/RAK-nRF52-RUI#8]
is it able to read the soc temperature?

if so how?

**Comment by beegee-tokyo** [comment]
Not implemented.
The underlaying nRF SDK has functions, but I have no examples how to use them.
You can have look at _**nrfx_temp.h**_ file, there are the functions. But no example how to use them. This is more a question towards Nordic.

**Comment by offizium-berndstorath** [comment]
```cpp
float read_nrf52_temperature(void)
{
	log("NRF52", "Reading temperature");

	int32_t value;
	uint32_t ret = sd_temp_get(&value);
	if (ret != NRF_SUCCESS)
	{
		log("NRF52", "Failed to read temperature");
	}
	
	float temp = static_cast<float>(value) / 4;
	log("NRF52", "T: %.2f", temp);

	return temp;
}
```
