### ISSUE TITLE
Support End-Device Status

### ISSUE THREAD

**Issue by offizium-berndstorath** [RAKWireless/RAK-nRF52-RUI#9]
In the Lorawan Spec there is End-Device Status. Unfortunately it isn't supported currently.

https://github.com/RAKWireless/RAK-nRF52-RUI/blob/3af00f8bae5b38c3febd7a5219e78ddf88301276/cores/nRF5/component/service/lora/service_lora.c#L895-L896

Please provide a way for the user to specify these values

**Comment by beegee-tokyo** [comment]
Answered you in the forum I guess [Support End-Device Status](https://forum.rakwireless.com/t/support-end-device-status/12966/7)

**Comment by offizium-berndstorath** [comment]
@beegee-tokyo your answer is not scalable in any way. manually editing this file on each installation is not a solution.

please provide a _method_ or api to be able to do this

**Comment by beegee-tokyo** [comment]
You are welcome to submit a pull-request, we have no plans at the moment to implement it.
